/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision: string | null }>;
};

clientsClaim();
self.skipWaiting();
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Route rules for Firebase (we ignore them so they go to network)
registerRoute(
  ({ request, url }: { request: Request; url: URL }) => {
    if (
      request.method !== 'GET' ||
      url.href.includes('firestore.googleapis.com') ||
      url.href.includes('firebase')
    ) {
      return true;
    }
    return false;
  },
  new NetworkFirst({
    cacheName: 'firebase-bypassed'
  })
);

// Fallback for standard fetches
registerRoute(
  ({ request }: { request: Request }) => request.destination === 'document' || request.destination === 'script' || request.destination === 'style' || request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'fj-tasks-cache',
  })
);

// ==== Firebase Cloud Messaging Initialization ====
importScripts('https://www.gstatic.com/firebasejs/10.9.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.9.0/firebase-messaging-compat.js');

const firebaseConfig = {
  apiKey: process.env.VITE_FIREBASE_API_KEY || "AIzaSyBkDV7zwUyxhhn58efVzYSQmCmIMxvyI-Q",
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || "dhlc-tasks.firebaseapp.com",
  projectId: process.env.VITE_FIREBASE_PROJECT_ID || "dhlc-tasks",
  storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || "dhlc-tasks.firebasestorage.app",
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "603469385752",
  appId: process.env.VITE_FIREBASE_APP_ID || "1:603469385752:web:54944a6533668540e0b36d",
  measurementId: process.env.VITE_FIREBASE_MEASUREMENT_ID || "G-8N9LKP69S5"
};

try {
  // @ts-ignore
  firebase.initializeApp(firebaseConfig);
  // @ts-ignore
  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload: any) => {
    console.log('[src/sw.ts] Received background message ', payload);
    
    const notificationTitle = payload.notification?.title || 'DHLC Tasks';
    const notificationOptions = {
      body: payload.notification?.body,
      icon: '/icons/icon-192.png',
      data: payload.data
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
  });
} catch (err) {
  console.error("Firebase messaging sw init failed:", err);
}
